name: parcial3_proyectos
description: A new Flutter project.


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  cached_network_image: ^3.1.0
  font_awesome_flutter:
  google_fonts: ^2.1.0
  intl:
  page_transition:
  timeago:
  url_launcher:
  http: any

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/